### ISSUE TITLE
Styling in chapter 14

### ISSUE THREAD

**Issue by acabal** [nwhetsell/george-macdonald_phantastes#10]
There's a blockquote in there with an ID, which is solely used to target the blockquote in CSS. Remove the ID, and instead target it with `class="inscription"`.

Additionally, convert the all-caps in the source to titlecase, and style the blockquote like so:

`.inscription p{ font-variant: small-caps; text-align: center; text-indent: 0; }`

Note that text-indent is required, otherwise it will be off-center.

**Comment by nwhetsell** [comment]
Instead of mentioning things like a “a blockquote in there”, please note that if you include a link like

```
https://github.com/nwhetsell/george-macdonald_phantastes/blob/b7d269c5361455e97ee22bb048a10c812c0625a3/src/epub/text/chapter-14.xhtml#L29
```

in your Markdown, you’ll get a link, filename, and excerpt like this:

https://github.com/nwhetsell/george-macdonald_phantastes/blob/b7d269c5361455e97ee22bb048a10c812c0625a3/src/epub/text/chapter-14.xhtml#L29

This is the only such inscription in the work, which is why I used an `id`. Still, I’ll fix it as requested.
